apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gpu-oj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gpu-oj-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          volumeMounts:
            - name: problems
              mountPath: /problems
      volumes:
        - name: problems
          persistentVolumeClaim:
            claimName: problems-pvc
